=== Vurnex/coursework/C# Second Year/First Class (Application Integration)/MidTermExam/students.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="Students">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="Student" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Name" type="xsd:string" maxOccurs="unbounded"/>
                        <xsd:element name="School" type="xsd:string" maxOccurs="unbounded"/>
                        <xsd:element name="Course" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="Hw1" type="xsd:string" maxOccurs="unbounded"/>
                                    <xsd:element name="Hw2" type="xsd:string" maxOccurs="unbounded"/>
                                    <xsd:element name="Hw3" type="xsd:string" maxOccurs="unbounded"/>
                                    <xsd:element name="Exam" type="xsd:string" maxOccurs="unbounded"/>
                                    <xsd:element name="Project" maxOccurs="unbounded">
                                        <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="ProjectName" type="xsd:string" maxOccurs="unbounded"/>
                                                <xsd:element name="ProjectScore" type="xsd:string" maxOccurs="unbounded"/>
                                            </xsd:sequence>
                                        </xsd:complexType>
                                    </xsd:element>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

</xsd:schema>

=== Vurnex/coursework/C# Second Year/First Class (Application Integration)/MidTermExam/midterm.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="students.xslt"?>

<Students   

  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="students.xsd">

  <Student>
    <Name>Student One</Name>
    <School>School</School>
    <Course>
      <Hw1>90</Hw1>
      <Hw2>80</Hw2>
      <Hw3>85</Hw3>
      <Exam>80</Exam>
      <Project>
        <ProjectName>Project 1</ProjectName>
        <ProjectScore>100</ProjectScore>
      </Project>
    </Course>
  </Student>
  <Student>
    <Name>Student Two</Name>
    <School>School</School>
    <Course>
      <Hw1>85</Hw1>
      <Hw2>80</Hw2>
      <Hw3>90</Hw3>
      <Exam>95</Exam>
      <Project>
        <ProjectName>Project 1</ProjectName>
        <ProjectScore>100</ProjectScore>
      </Project>
    </Course>
  </Student>
</Students>
